# Generated by Django 5.1.1 on 2024-10-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speedrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.CharField(max_length=40)),
                ('tiempo', models.IntegerField()),
                ('link', models.CharField(max_length=80)),
            ],
        ),
    ]
