# Generated by Django 5.1.1 on 2024-10-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_speedrun_tiempo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speedrun',
        ),
    ]
