# Generated by Django 5.1.1 on 2024-11-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_nickname_usuario_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='e_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
